---
- name: Create data directory
  file:
      dest: "{{ base_dir }}/telegraf"
      state: "directory"

- name: Create config
  template:
      src: "{{ item }}.j2"
      dest: "{{ base_dir }}/telegraf/{{ item }}"
      owner: root
      mode: 0600
  with_items:
      - telegraf.conf
      - Dockerfile
  register: config_file

- name: Copy who.sh script
  copy:
    src: "who.sh"
    dest: "{{ base_dir }}/telegraf/who.sh"
    mode: 0555
  register: who_script

- name: Build image
  docker_image:
      path: "{{ base_dir }}/telegraf"
      name: telegraf
      force: "{{ 'yes' if config_file.changed or who_script.changed or force_update | default(false) else 'no' }}"
      tag: "{{ telegraf_version }}-custom"
  register: build_image

- name: Get hostname
  command: hostname
  register: hostname

- name: Set volumes
  set_fact:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/sys:/rootfs/sys:ro"
      - "/proc:/rootfs/proc:ro"
      - "/etc:/rootfs/etc:ro"
      - "/var/run/utmp:/var/run/utmp:ro"
      #- "{{ base_dir }}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"

- name: Append if fail2ban volumes
  set_fact:
    volumes: "{{ volumes  + ['/var/run/fail2ban/fail2ban.sock:/var/run/fail2ban/fail2ban.sock:ro'] }}"
  when: inventory_hostname in groups['fail2ban']|default([])

- name: Start container
  docker_container:
      image: "telegraf:{{ telegraf_version }}-custom"
      name: telegraf
      recreate: "{{ 'yes' if build_image.changed or hostname.changed or force_update else 'no' }}"
      user: root
      hostname: "{{ hostname.stdout }}"
      restart_policy: always
      network_mode: host
      etc_hosts:
          nginx.dreamkas.ru: 127.0.0.1
      env:
          HOST_PROC: /rootfs/proc
          HOST_SYS: /rootfs/sys
          HOST_ETC: /rootfs/etc
      log_driver: json-file
      log_options:
          max-size: "1m"
          max-file: "1"
      volumes: "{{ volumes }}"
